window.contestOpsData = {
  product: 'ContestOps AI',
  version: '0.4.0',
  prod: 81,
  milestone: {
    title: 'Foundation package',
    percent: 62,
    target: '2026-05-29',
  },
  deadline: '2026-08-17 1:00 PM PDT',
  opportunity: 'Build with Gemini XPRIZE',
  category: 'Entrepreneurship & Job Creation',
  metrics: [
    { label: 'Rules', value: '18/32', tone: 'teal' },
    { label: 'Evidence', value: '14/26', tone: 'amber' },
    { label: 'Users', value: 'TBD', tone: 'slate' },
    { label: 'Revenue', value: 'TBD', tone: 'red' },
  ],
  runs: [
    { time: '2026-05-29', name: 'Rules package', status: 'done' },
    { time: '2026-05-29', name: 'V manifest', status: 'done' },
    { time: '2026-05-29', name: 'Gemini smoke', status: 'mock' },
    { time: '2026-05-29', name: 'Cloud Run API', status: 'done' },
    { time: '2026-05-29', name: 'Judge scorecard', status: 'done' },
  ],
  checklist: [
    { title: 'Gemini API deployed LLM call', status: 'active', owner: 'core' },
    { title: 'Google Cloud product receipt', status: 'planned', owner: 'deploy' },
    { title: 'Public or judge-shared repo', status: 'planned', owner: 'release' },
    { title: 'Revenue monthly breakdown', status: 'planned', owner: 'sales' },
    { title: 'Real user feedback and consent', status: 'planned', owner: 'pilot' },
    { title: 'Sub-3-minute demo video', status: 'planned', owner: 'media' },
  ],
  evidence: [
    { name: 'V manifest', state: 'active', path: 'contestops_ai/out' },
    { name: 'Devpost payload', state: 'active', path: 'submission/devpost_payload.json' },
    { name: 'WAIBAv trace', state: 'active', path: 'automation/output' },
    { name: 'Gemini receipt', state: 'active', path: 'evidence/gemini_call_receipts' },
    { name: 'Revenue ledger', state: 'planned', path: 'evidence/private/revenue' },
    { name: 'User ledger', state: 'planned', path: 'evidence/private/users' },
  ],
  automations: [
    { name: 'Devpost draft prepare', type: 'WAIBAv', state: 'validating' },
    { name: 'Form field map', type: 'YAML', state: 'ready' },
    { name: 'Final submit receipt', type: 'WAIBAv', state: 'scheduled' },
  ],
  scorecard: [
    { label: 'Business Viability', score: 58, gap: 'Close 3 independent paid pilots.' },
    { label: 'AI-Native Operations', score: 86, gap: 'Run real Gemini and Cloud receipts.' },
    { label: 'Category Impact', score: 82, gap: 'Quantify founder outcomes.' },
    { label: 'Differentiation', score: 88, gap: 'Publish one redacted case study.' },
  ],
  competitors: [
    {
      name: 'Vertical AI startup with revenue',
      threat: 92,
      counter: 'Show AI operating the whole business with receipts.',
    },
    {
      name: 'Generic agent platform',
      threat: 84,
      counter: 'Win with a focused founder-ops wedge and paid pilots.',
    },
    {
      name: 'Proposal-writing assistant',
      threat: 78,
      counter: 'Show execution, evidence, and form automation beyond drafting.',
    },
    {
      name: 'AI devtool startup',
      threat: 76,
      counter: 'Show economic opportunity for nontechnical founders.',
    },
  ],
};
